### ISSUE TITLE
This is the best repo ever

### ISSUE THREAD

**Issue by Manbearpiet** [Dutch-DOG/DDOG#4]
![afbeelding](https://user-images.githubusercontent.com/43993129/90172510-67da7800-dda3-11ea-9aef-661ab96505c0.png)

**Comment by dutchdog** [comment]
:dog: Hello Manbearpiet, Welcome to DDOG! :sparkles: :smiley:.  

This message is automatically created.  
Want to create your own GitHub Issue autoreply? Find the code [HERE](https://github.com/Dutch-DOG/DDOG/).
